#!/bin/bash
# --------------------------------------------------------------------------- #
#   ==   ===  ==                                                              #
#  ||   ||=  || ))  support s. r. o. 2014, www.cfdsupport.com                 #
#   ==        ==                                                              #
# --------------------------------------------------------------------------- #

# This script will duplicate template directory train-mesh.org to train-mesh
# and create a computational mesh inside the new directory.

# check OpenFOAM environment
if [[ $(echo $WM_PROJECT_VERSION | cut -c1-3) != "3.0" ]]
then
    echo "Use OpenFOAM 3.0 with this example script, please."
    exit
fi

# copy template directory if no present
if [[ ! -d train-mesh ]]
then
    cp -r train-mesh.org train-mesh
fi

# mesh creation
cd train-mesh
./makeMesh
cd ..
