#!/bin/bash
# --------------------------------------------------------------------------- #
#   ==   ===  ==                                                              #
#  ||   ||=  || ))  support s. r. o. 2014, www.cfdsupport.com                 #
#   ==        ==                                                              #
# --------------------------------------------------------------------------- #

# This script will duplicate the template directory train-case-stationary.org
# to train-case-stationary and run the steady-state case inside the newly
# created directory.

# check OpenFOAM environment
#if [[ $(echo $WM_PROJECT_VERSION | cut -c1-3) != "3.0" ]]
#then
#    echo "Use OpenFOAM 3.0 with this example script, please."
#    exit
#fi

# copy template directory if not present
if [[ ! -d train-case-stationary ]]
then
    cp -r train-case-stationary.org train-case-stationary
fi

# run the stationary case
cd train-case-stationary
./Allrun
cd ..
