#!/bin/bash
# --------------------------------------------------------------------------- #
#   ==   ===  ==                                                              #
#  ||   ||=  || ))  support s. r. o. 2014, www.cfdsupport.com                 #
#   ==        ==                                                              #
# --------------------------------------------------------------------------- #

# copy mesh and initial conditions
echo " 1. Initialize the case."
rm -rf 0 log.all constant/polyMesh processor*
cp -r 0.org 0
if [[ ! -f ../train-mesh/last/polyMesh/boundary ]]
then
    echo "Mesh not found in train-mesh/last."
    exit
fi
cp -rf ./../train-mesh/last/polyMesh ./constant/polyMesh

# decompose and compute
echo " 2. Parallel decomposition."
decomposePar | tee -a log.all > decomposePar.log
echo " 4. Mesh optimization (renumberMesh)."
mpiexec -np 4 renumberMesh -parallel -overwrite | tee -a log.all > renumberMesh.log
echo " 5. Steady-state simulation (simpleFoam)."
mpiexec -np 4 pimpleDyMFoam -parallel | tee -a log.all > simpleFoam.log
echo " 6. Parallel reconstruction."
#reconstructPar -latestTime | tee -a log.all > reconstructPar.log
reconstructPar | tee -a log.all > reconstructPar.log
